version: '3.7'

services:
  master:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - 4406:3306
    volumes:
      - ./master/data:/var/lib/mysql
      - ./backups:/backups
      - ./master/master.cnf:/etc/mysql/mariadb.conf.d/master.cnf
      - ./scripts:/scripts
    networks:
      - myNetwork

  slave:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 111
    ports:
      - 5506:3306
    depends_on:
      - master
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./backups:/backups
      - ./slave/slave.cnf:/etc/mysql/mariadb.conf.d/slave.cnf
      - ./scripts:/scripts
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
