version: '3.7'

services:
  mariadb:
    image: mariadb:10.5
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    ports:
      - 9104
    environment:
      DATA_SOURCE_NAME: root:password@(mariadb:3306)/db
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
